### PR TITLE
more quiet, log messages to stderr

### PR DESCRIPTION
**Pull request by kovetskiy**
Hi. It's me again.

Quiet mode (-quiet flag) did not work in some cases (keyboard found messages).

### CODE REVIEW

**Comment by grafov** [comment]
Nice to see that this stuff is still used :) Thank you for the patch!

**Comment by seletskiy** [comment]
@grafov: What do you use?

**Comment by grafov** [comment]
I still use this utility too, it satisfy my needs as language switcher. Just thinking about more configurable event mapper for whole keyboard. It would be nice to apply key mappings to miscellaneous input devices. For example I want to use computer pedal (that I have bought recently) as modifier for my laptop keyboard  or as an alternative key for mouse. It seems it is hard (and probably impossible) with xkb, it can't mix modifiers for different devices. But I think it would possible on lower level with evdev protocol.

**Comment by kovetskiy** [comment]
We did pedal footswitch with xkb already: https://github.com/reconquest/rex (@seletskiy can you link on specific symbols/keycodes for footswitch?)

By the way, we dont use mouse at all, we are using keynav (http://www.semicomplete.com/projects/keynav), our configurations that we use for previous 2 years can be found here:
https://github.com/kovetskiy/dotfiles/blob/master/.keynavrc
https://github.com/seletskiy/dotfiles/blob/master/.keynavrc

Actually, shift-shift sometimes can't switch as quickly as I want, and I don't know what to do with it unless type slower, may be rewrote some parts of shift-shift to C (using cgo or pure C).

**Comment by grafov** [comment]
Thank you for pointing to XKB hacks, it is very useful. keynav looks very interesting approach too. I will take a look into them. Most of time I spend in Emacs which has its own ways for quick screen navigation. For other apps (mainly web browser) I use mouse (exactly it is trackball). It is good enough for me especially with tiling WM. Though stop using mouse at all looks like a promising idea.

Really shift-shift in some cases doesn't switch layout so it required press shift again. I not sure the problem is in speed of go app, maybe I handle evdev events not properly or used X calls in wrong way. I have not found a time for debugging it yet. Though golang still is my main language for last years I agree pure C solution is good for such task that specific for X internals.

**Comment by seletskiy** [comment]
Footswitch configuration is available through `footswitch` program: https://github.com/seletskiy/dotfiles/blob/master/bin/reconfig-kbd#L18 (https://github.com/rgerganov/footswitch). It maps pedals to keycodes (I use F6-F8), that then mapped to language switch (https://github.com/reconquest/rex/blob/master/symbols/footswitch).

**Comment by seletskiy** [comment]
@grafov: Regarding switching issue in `shift-shift` — I've debugged that issue and as far as I can remember, problem was that input stream from keyboard to application (e.g. typing experience) is completely asynchronous to reading evdev events and then switching layout. So, in current architecture there is no clear way of avoiding that issue altogether, and pure C solution will not fix it, because problem there is that we can't (or can we?) block user input until `shift-shift` will do layout switch.

**Pull request merged**
